version: '3.0'

services:
  nginx-proxy:
    image: nginx:1.25.2
    container_name: nginx-proxy
    restart: always
    ports:
      - "443:443"
    volumes:
      - /opt/services/conf/nginx.conf:/etc/nginx/nginx.conf
      - /opt/services/certs:/etc/nginx/certs
      - /opt/services/vhost.d:/etc/nginx/vhost.d
      - /opt/services/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /opt/services/logs:/opt/bitnami/nginx/logs
    user: root:root
    networks:
      - services_net

  memcached:
    image: memcached:1.6.20
    container_name: memcached
    restart: always
    networks:
      - services_net

  yopass:
    image: jhaals/yopass:11.15.0
    container_name: yopass
    restart: always
    environment:
      - VIRTUAL_HOST=domain_name  #Put the domain name you would like to have for e.g. yopass.com
    command: "--memcached=memcached:11211 --port 8082"
    networks:
      - services_net

networks:
  services_net:
    driver: bridge
